info:
  service:
    name: @project.artifactId@
    version: @project.version@

spring:
  profiles:
    active: dev-local

springfox:
  documentation:
    enabled: true
    swaggerUi:
      baseUrl: /internal/documentation
    openApi:
      v3:
        path: /internal/documentation/v3/api-docs
    swagger:
      v2:
        path: /internal/documentation/v2/api-docs


image-upload:
  s3-bucket: ana-management-images
  cloudfront-distribution-base-url: https://d8wp2lccw6r09.cloudfront.net

jwt:
  aws:
    user-pool-id: ${USER_POOL_ID}
    region: us-east-1

management:
  endpoint:
    health:
      enabled: true
  health:
    defaults:
      enabled: true

